// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `1c-light` theme.
const $1cLightTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#0000ff', backgroundColor: '#ffffff'),
  'addition': HljsStyle(color: '#0000ff'),
  'attribute': HljsStyle(color: '#ff0000'),
  'built_in': HljsStyle(color: '#0000ff'),
  'bullet': HljsStyle(color: '#0000ff'),
  'code': HljsStyle(color: '#0000ff'),
  'comment': HljsStyle(color: '#008000'),
  'deletion': HljsStyle(color: '#000000'),
  'doctag': HljsStyle(color: '#ff0000'),
  'emphasis': HljsStyle(italic: true),
  'function': HljsStyle(color: '#ff0000'),
  'keyword': HljsStyle(color: '#ff0000'),
  'link': HljsStyle(color: '#ab5656'),
  'literal': HljsStyle(color: '#ff0000'),
  'meta': HljsStyle(color: '#963200'),
  'meta keyword': HljsStyle(color: '#963200'),
  'meta string': HljsStyle(color: '#963200'),
  'name': HljsStyle(color: '#ff0000'),
  'number': HljsStyle(color: '#000000'),
  'operator': HljsStyle(color: '#ab5656'),
  'params': HljsStyle(color: '#0000ff'),
  'punctuation': HljsStyle(color: '#ff0000'),
  'quote': HljsStyle(color: '#000000'),
  'regexp': HljsStyle(color: '#ab5656'),
  'section': HljsStyle(color: '#0000ff'),
  'selector-attr': HljsStyle(color: '#ab5656'),
  'selector-class': HljsStyle(color: '#000000'),
  'selector-id': HljsStyle(color: '#000000'),
  'selector-pseudo': HljsStyle(color: '#ab5656'),
  'selector-tag': HljsStyle(color: '#ff0000'),
  'string': HljsStyle(color: '#000000'),
  'strong': HljsStyle(bold: true),
  'symbol': HljsStyle(color: '#000000'),
  'tag': HljsStyle(color: '#444444'),
  'tag attr': HljsStyle(color: '#444444'),
  'tag name': HljsStyle(color: '#444444'),
  'template-tag': HljsStyle(color: '#000000'),
  'template-variable': HljsStyle(color: '#ab5656'),
  'title': HljsStyle(color: '#0000ff'),
  'type': HljsStyle(color: '#0000ff'),
  'variable': HljsStyle(color: '#ab5656'),
};
