// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `atom-one-dark-reasonable` theme.
const atomOneDarkReasonableTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#abb2bf', backgroundColor: '#282c34'),
  'addition': HljsStyle(color: '#98c379'),
  'attr': HljsStyle(color: '#d19a66'),
  'attribute': HljsStyle(color: '#98c379'),
  'built_in': HljsStyle(color: '#e6c07b'),
  'bullet': HljsStyle(color: '#61aeee'),
  'comment': HljsStyle(color: '#b18eb1', italic: true),
  'constructor': HljsStyle(color: '#e2b93d'),
  'constructor string': HljsStyle(color: '#9ccc65'),
  'deletion': HljsStyle(color: '#e06c75'),
  'doctag': HljsStyle(color: '#c678dd'),
  'emphasis': HljsStyle(italic: true),
  'formula': HljsStyle(color: '#c678dd'),
  'function': HljsStyle(color: '#61aeee'),
  'keyword': HljsStyle(color: '#f92672'),
  'link': HljsStyle(color: '#61aeee', underline: true),
  'literal': HljsStyle(color: '#56b6c2'),
  'meta': HljsStyle(color: '#61aeee'),
  'meta string': HljsStyle(color: '#98c379'),
  'module-access module': HljsStyle(color: '#7e57c2'),
  'name': HljsStyle(color: '#e06c75'),
  'number': HljsStyle(color: '#d19a66'),
  'operator': HljsStyle(color: '#f92672'),
  'pattern-match': HljsStyle(color: '#f92672'),
  'pattern-match constructor': HljsStyle(color: '#61aeee'),
  'quote': HljsStyle(color: '#b18eb1', italic: true),
  'regexp': HljsStyle(color: '#98c379'),
  'section': HljsStyle(color: '#e06c75'),
  'selector-attr': HljsStyle(color: '#d19a66'),
  'selector-class': HljsStyle(color: '#d19a66'),
  'selector-id': HljsStyle(color: '#61aeee'),
  'selector-pseudo': HljsStyle(color: '#d19a66'),
  'selector-tag': HljsStyle(color: '#e06c75'),
  'string': HljsStyle(color: '#98c379'),
  'strong': HljsStyle(bold: true),
  'subst': HljsStyle(color: '#e06c75'),
  'symbol': HljsStyle(color: '#61aeee'),
  'template-variable': HljsStyle(color: '#d19a66'),
  'title': HljsStyle(color: '#61aeee'),
  'title.class': HljsStyle(color: '#e6c07b'),
  'type': HljsStyle(color: '#d19a66'),
  'variable': HljsStyle(color: '#d19a66'),
};
