// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `devibeans` theme.
const devibeansTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#a39e9b', backgroundColor: '#000000'),
  'addition': HljsStyle(color: '#558b2f'),
  'attr': HljsStyle(color: '#8787d7'),
  'attribute': HljsStyle(color: '#ffd75f'),
  'built_in': HljsStyle(color: '#ff8700'),
  'bullet': HljsStyle(color: '#558b2f'),
  'code': HljsStyle(color: '#64b5f6'),
  'comment': HljsStyle(color: '#339966'),
  'deletion': HljsStyle(color: '#ff8700'),
  'doctag': HljsStyle(color: '#339966'),
  'emphasis': HljsStyle(italic: true),
  'formula': HljsStyle(color: '#64b5f6'),
  'function': HljsStyle(color: '#ffd75f'),
  'keyword': HljsStyle(color: '#64b5f6'),
  'link': HljsStyle(color: '#64b5f6'),
  'literal': HljsStyle(color: '#ef5350'),
  'meta': HljsStyle(color: '#0087ff'),
  'meta keyword': HljsStyle(color: '#0087ff'),
  'meta string': HljsStyle(color: '#558b2f'),
  'name': HljsStyle(color: '#ffd75f'),
  'number': HljsStyle(color: '#ef5350'),
  'params': HljsStyle(color: '#a39e9b'),
  'property': HljsStyle(color: '#ffd75f'),
  'quote': HljsStyle(color: '#339966'),
  'regexp': HljsStyle(color: '#d700ff'),
  'section': HljsStyle(color: '#ffd75f'),
  'selector-attr': HljsStyle(color: '#64b5f6'),
  'selector-class': HljsStyle(color: '#64b5f6'),
  'selector-id': HljsStyle(color: '#ef5350'),
  'selector-pseudo': HljsStyle(color: '#64b5f6'),
  'selector-tag': HljsStyle(color: '#9966ff'),
  'string': HljsStyle(color: '#558b2f'),
  'strong': HljsStyle(bold: true),
  'subst': HljsStyle(color: '#558b2f'),
  'symbol': HljsStyle(color: '#558b2f'),
  'tag': HljsStyle(color: '#ef5350'),
  'template-tag': HljsStyle(color: '#8787d7'),
  'template-variable': HljsStyle(color: '#64b5f6'),
  'title': HljsStyle(color: '#ff8700'),
  'type': HljsStyle(color: '#ffd75f'),
  'variable': HljsStyle(color: '#64b5f6'),
};
