// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `github-dark` theme.
const githubDarkTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#c9d1d9', backgroundColor: '#0d1117'),
  'addition': HljsStyle(color: '#aff5b4', backgroundColor: '#033a16'),
  'attr': HljsStyle(color: '#79c0ff'),
  'attribute': HljsStyle(color: '#79c0ff'),
  'built_in': HljsStyle(color: '#ffa657'),
  'bullet': HljsStyle(color: '#f2cc60'),
  'code': HljsStyle(color: '#8b949e'),
  'comment': HljsStyle(color: '#8b949e'),
  'deletion': HljsStyle(color: '#ffdcd7', backgroundColor: '#67060c'),
  'doctag': HljsStyle(color: '#ff7b72'),
  'emphasis': HljsStyle(color: '#c9d1d9', italic: true),
  'formula': HljsStyle(color: '#8b949e'),
  'keyword': HljsStyle(color: '#ff7b72'),
  'literal': HljsStyle(color: '#79c0ff'),
  'meta': HljsStyle(color: '#79c0ff'),
  'meta keyword': HljsStyle(color: '#ff7b72'),
  'meta string': HljsStyle(color: '#a5d6ff'),
  'name': HljsStyle(color: '#7ee787'),
  'number': HljsStyle(color: '#79c0ff'),
  'operator': HljsStyle(color: '#79c0ff'),
  'quote': HljsStyle(color: '#7ee787'),
  'regexp': HljsStyle(color: '#a5d6ff'),
  'section': HljsStyle(color: '#1f6feb', bold: true),
  'selector-attr': HljsStyle(color: '#79c0ff'),
  'selector-class': HljsStyle(color: '#79c0ff'),
  'selector-id': HljsStyle(color: '#79c0ff'),
  'selector-pseudo': HljsStyle(color: '#7ee787'),
  'selector-tag': HljsStyle(color: '#7ee787'),
  'string': HljsStyle(color: '#a5d6ff'),
  'strong': HljsStyle(color: '#c9d1d9', bold: true),
  'subst': HljsStyle(color: '#c9d1d9'),
  'symbol': HljsStyle(color: '#ffa657'),
  'template-tag': HljsStyle(color: '#ff7b72'),
  'template-variable': HljsStyle(color: '#ff7b72'),
  'title': HljsStyle(color: '#d2a8ff'),
  'title.class': HljsStyle(color: '#d2a8ff'),
  'title.class.inherited': HljsStyle(color: '#d2a8ff'),
  'title.function': HljsStyle(color: '#d2a8ff'),
  'type': HljsStyle(color: '#ff7b72'),
  'variable': HljsStyle(color: '#79c0ff'),
  'variable.language': HljsStyle(color: '#ff7b72'),
};
