// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `github-dark-dimmed` theme.
const githubDarkDimmedTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#adbac7', backgroundColor: '#22272e'),
  'addition': HljsStyle(color: '#b4f1b4', backgroundColor: '#1b4721'),
  'attr': HljsStyle(color: '#6cb6ff'),
  'attribute': HljsStyle(color: '#6cb6ff'),
  'built_in': HljsStyle(color: '#f69d50'),
  'bullet': HljsStyle(color: '#eac55f'),
  'code': HljsStyle(color: '#768390'),
  'comment': HljsStyle(color: '#768390'),
  'deletion': HljsStyle(color: '#ffd8d3', backgroundColor: '#78191b'),
  'doctag': HljsStyle(color: '#f47067'),
  'emphasis': HljsStyle(color: '#adbac7', italic: true),
  'formula': HljsStyle(color: '#768390'),
  'keyword': HljsStyle(color: '#f47067'),
  'literal': HljsStyle(color: '#6cb6ff'),
  'meta': HljsStyle(color: '#6cb6ff'),
  'meta keyword': HljsStyle(color: '#f47067'),
  'meta string': HljsStyle(color: '#96d0ff'),
  'name': HljsStyle(color: '#8ddb8c'),
  'number': HljsStyle(color: '#6cb6ff'),
  'operator': HljsStyle(color: '#6cb6ff'),
  'quote': HljsStyle(color: '#8ddb8c'),
  'regexp': HljsStyle(color: '#96d0ff'),
  'section': HljsStyle(color: '#316dca', bold: true),
  'selector-attr': HljsStyle(color: '#6cb6ff'),
  'selector-class': HljsStyle(color: '#6cb6ff'),
  'selector-id': HljsStyle(color: '#6cb6ff'),
  'selector-pseudo': HljsStyle(color: '#8ddb8c'),
  'selector-tag': HljsStyle(color: '#8ddb8c'),
  'string': HljsStyle(color: '#96d0ff'),
  'strong': HljsStyle(color: '#adbac7', bold: true),
  'subst': HljsStyle(color: '#adbac7'),
  'symbol': HljsStyle(color: '#f69d50'),
  'template-tag': HljsStyle(color: '#f47067'),
  'template-variable': HljsStyle(color: '#f47067'),
  'title': HljsStyle(color: '#dcbdfb'),
  'title.class': HljsStyle(color: '#dcbdfb'),
  'title.class.inherited': HljsStyle(color: '#dcbdfb'),
  'title.function': HljsStyle(color: '#dcbdfb'),
  'type': HljsStyle(color: '#f47067'),
  'variable': HljsStyle(color: '#6cb6ff'),
  'variable.language': HljsStyle(color: '#f47067'),
};
