// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `github` theme.
const githubTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#24292e', backgroundColor: '#ffffff'),
  'addition': HljsStyle(color: '#22863a', backgroundColor: '#f0fff4'),
  'attr': HljsStyle(color: '#005cc5'),
  'attribute': HljsStyle(color: '#005cc5'),
  'built_in': HljsStyle(color: '#e36209'),
  'bullet': HljsStyle(color: '#735c0f'),
  'code': HljsStyle(color: '#6a737d'),
  'comment': HljsStyle(color: '#6a737d'),
  'deletion': HljsStyle(color: '#b31d28', backgroundColor: '#ffeef0'),
  'doctag': HljsStyle(color: '#d73a49'),
  'emphasis': HljsStyle(color: '#24292e', italic: true),
  'formula': HljsStyle(color: '#6a737d'),
  'keyword': HljsStyle(color: '#d73a49'),
  'literal': HljsStyle(color: '#005cc5'),
  'meta': HljsStyle(color: '#005cc5'),
  'meta keyword': HljsStyle(color: '#d73a49'),
  'meta string': HljsStyle(color: '#032f62'),
  'name': HljsStyle(color: '#22863a'),
  'number': HljsStyle(color: '#005cc5'),
  'operator': HljsStyle(color: '#005cc5'),
  'quote': HljsStyle(color: '#22863a'),
  'regexp': HljsStyle(color: '#032f62'),
  'section': HljsStyle(color: '#005cc5', bold: true),
  'selector-attr': HljsStyle(color: '#005cc5'),
  'selector-class': HljsStyle(color: '#005cc5'),
  'selector-id': HljsStyle(color: '#005cc5'),
  'selector-pseudo': HljsStyle(color: '#22863a'),
  'selector-tag': HljsStyle(color: '#22863a'),
  'string': HljsStyle(color: '#032f62'),
  'strong': HljsStyle(color: '#24292e', bold: true),
  'subst': HljsStyle(color: '#24292e'),
  'symbol': HljsStyle(color: '#e36209'),
  'template-tag': HljsStyle(color: '#d73a49'),
  'template-variable': HljsStyle(color: '#d73a49'),
  'title': HljsStyle(color: '#6f42c1'),
  'title.class': HljsStyle(color: '#6f42c1'),
  'title.class.inherited': HljsStyle(color: '#6f42c1'),
  'title.function': HljsStyle(color: '#6f42c1'),
  'type': HljsStyle(color: '#d73a49'),
  'variable': HljsStyle(color: '#005cc5'),
  'variable.language': HljsStyle(color: '#d73a49'),
};
