// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `night-owl` theme.
const nightOwlTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#d6deeb', backgroundColor: '#011627'),
  'addition': HljsStyle(color: '#addb67', italic: true),
  'attr': HljsStyle(color: '#7fdbca'),
  'attribute': HljsStyle(color: '#80cbc4'),
  'built_in': HljsStyle(color: '#addb67', italic: true),
  'bullet': HljsStyle(color: '#d9f5dd'),
  'class': HljsStyle(color: '#ffcb8b'),
  'code': HljsStyle(color: '#80cbc4'),
  'comment': HljsStyle(color: '#637777', italic: true),
  'deletion': HljsStyle(color: '#ef5350', italic: true),
  'doctag': HljsStyle(color: '#7fdbca'),
  'emphasis': HljsStyle(color: '#c792ea', italic: true),
  'formula': HljsStyle(color: '#c792ea'),
  'function': HljsStyle(color: '#82aaff'),
  'keyword': HljsStyle(color: '#c792ea', italic: true),
  'link': HljsStyle(color: '#ff869a'),
  'literal': HljsStyle(color: '#ff5874'),
  'meta': HljsStyle(color: '#82aaff'),
  'meta keyword': HljsStyle(color: '#82aaff'),
  'meta string': HljsStyle(color: '#ecc48d'),
  'name': HljsStyle(color: '#7fdbca'),
  'number': HljsStyle(color: '#f78c6c'),
  'params': HljsStyle(color: '#7fdbca'),
  'quote': HljsStyle(color: '#697098', italic: true),
  'regexp': HljsStyle(color: '#5ca7e4'),
  'section': HljsStyle(color: '#82b1ff'),
  'selector-attr': HljsStyle(color: '#c792ea', italic: true),
  'selector-class': HljsStyle(color: '#addb67', italic: true),
  'selector-id': HljsStyle(color: '#fad430'),
  'selector-pseudo': HljsStyle(color: '#c792ea', italic: true),
  'selector-tag': HljsStyle(color: '#ff6363'),
  'string': HljsStyle(color: '#ecc48d'),
  'strong': HljsStyle(color: '#addb67', bold: true),
  'subst': HljsStyle(color: '#d3423e'),
  'symbol': HljsStyle(color: '#82aaff'),
  'tag': HljsStyle(color: '#7fdbca'),
  'template-tag': HljsStyle(color: '#c792ea'),
  'template-variable': HljsStyle(color: '#addb67'),
  'title': HljsStyle(color: '#dcdcaa', italic: true),
  'type': HljsStyle(color: '#82aaff'),
  'variable': HljsStyle(color: '#addb67'),
};
