// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `panda-syntax-dark` theme.
const pandaSyntaxDarkTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#e6e6e6', backgroundColor: '#2a2c2d'),
  'addition': HljsStyle(color: '#19f9d8'),
  'attr': HljsStyle(color: '#e6e6e6'),
  'attribute': HljsStyle(color: '#ffb86c'),
  'built_in': HljsStyle(color: '#ffb86c'),
  'bullet': HljsStyle(color: '#19f9d8'),
  'char.escape': HljsStyle(color: '#b084eb'),
  'code': HljsStyle(color: '#45a9f9'),
  'comment': HljsStyle(color: '#bbbbbb', italic: true),
  'deletion': HljsStyle(color: '#ff75b5'),
  'doctag': HljsStyle(color: '#ffb86c'),
  'emphasis': HljsStyle(italic: true),
  'formula': HljsStyle(color: '#45a9f9'),
  'keyword': HljsStyle(color: '#ff75b5'),
  'link': HljsStyle(color: '#ffb86c', underline: true),
  'literal': HljsStyle(color: '#ffb86c'),
  'meta': HljsStyle(color: '#ff4b82'),
  'meta keyword': HljsStyle(color: '#ffb86c'),
  'meta string': HljsStyle(color: '#19f9d8'),
  'name': HljsStyle(color: '#ff4b82'),
  'number': HljsStyle(color: '#ffb86c'),
  'operator': HljsStyle(color: '#b084eb'),
  'params': HljsStyle(color: '#bbbbbb'),
  'property': HljsStyle(color: '#45a9f9'),
  'punctuation': HljsStyle(color: '#ffb86c'),
  'quote': HljsStyle(color: '#bbbbbb', italic: true),
  'regexp': HljsStyle(color: '#ff9ac1'),
  'section': HljsStyle(color: '#45a9f9'),
  'selector-attr': HljsStyle(color: '#ff9ac1'),
  'selector-class': HljsStyle(color: '#19f9d8'),
  'selector-id': HljsStyle(color: '#ffb86c'),
  'selector-pseudo': HljsStyle(color: '#ff9ac1'),
  'selector-tag': HljsStyle(color: '#ff4b82'),
  'string': HljsStyle(color: '#19f9d8'),
  'strong': HljsStyle(bold: true),
  'subst': HljsStyle(color: '#45a9f9'),
  'symbol': HljsStyle(color: '#19f9d8'),
  'tag': HljsStyle(color: '#ffb86c'),
  'template-tag': HljsStyle(color: '#ffb86c'),
  'template-variable': HljsStyle(color: '#ffb86c'),
  'title': HljsStyle(color: '#ffb86c'),
  'title.class': HljsStyle(color: '#19f9d8'),
  'title.class.inherited': HljsStyle(color: '#19f9d8'),
  'title.function': HljsStyle(color: '#45a9f9'),
  'type': HljsStyle(color: '#ffb86c'),
  'variable': HljsStyle(color: '#ffb86c'),
  'variable.language': HljsStyle(color: '#ff9ac1'),
};
