// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `panda-syntax-light` theme.
const pandaSyntaxLightTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#2a2c2d', backgroundColor: '#e6e6e6'),
  'addition': HljsStyle(color: '#0d7d6c'),
  'attr': HljsStyle(color: '#2a2c2d'),
  'attribute': HljsStyle(color: '#7641bb'),
  'built_in': HljsStyle(color: '#7641bb'),
  'bullet': HljsStyle(color: '#0d7d6c'),
  'char.escape': HljsStyle(color: '#c56200'),
  'code': HljsStyle(color: '#3787c7'),
  'comment': HljsStyle(color: '#676b79', italic: true),
  'deletion': HljsStyle(color: '#d92792'),
  'doctag': HljsStyle(color: '#7641bb'),
  'emphasis': HljsStyle(italic: true),
  'formula': HljsStyle(color: '#3787c7'),
  'keyword': HljsStyle(color: '#d92792'),
  'link': HljsStyle(color: '#7641bb', underline: true),
  'literal': HljsStyle(color: '#7641bb'),
  'meta': HljsStyle(color: '#c56200'),
  'meta keyword': HljsStyle(color: '#7641bb'),
  'meta string': HljsStyle(color: '#0d7d6c'),
  'name': HljsStyle(color: '#c56200'),
  'number': HljsStyle(color: '#7641bb'),
  'operator': HljsStyle(color: '#c56200'),
  'params': HljsStyle(color: '#676b79'),
  'property': HljsStyle(color: '#3787c7'),
  'punctuation': HljsStyle(color: '#2a2c2d'),
  'quote': HljsStyle(color: '#676b79', italic: true),
  'regexp': HljsStyle(color: '#cc5e91'),
  'section': HljsStyle(color: '#3787c7'),
  'selector-attr': HljsStyle(color: '#cc5e91'),
  'selector-class': HljsStyle(color: '#0d7d6c'),
  'selector-id': HljsStyle(color: '#7641bb'),
  'selector-pseudo': HljsStyle(color: '#cc5e91'),
  'selector-tag': HljsStyle(color: '#c56200'),
  'string': HljsStyle(color: '#0d7d6c'),
  'strong': HljsStyle(bold: true),
  'subst': HljsStyle(color: '#3787c7'),
  'symbol': HljsStyle(color: '#0d7d6c'),
  'tag': HljsStyle(color: '#7641bb'),
  'template-tag': HljsStyle(color: '#7641bb'),
  'template-variable': HljsStyle(color: '#7641bb'),
  'title': HljsStyle(color: '#7641bb'),
  'title.class': HljsStyle(color: '#0d7d6c'),
  'title.class.inherited': HljsStyle(color: '#0d7d6c'),
  'title.function': HljsStyle(color: '#3787c7'),
  'type': HljsStyle(color: '#7641bb'),
  'variable': HljsStyle(color: '#7641bb'),
  'variable.language': HljsStyle(color: '#cc5e91'),
};
