// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `rose-pine` theme.
const rosePineTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#6e6a86', backgroundColor: '#191724'),
  'addition': HljsStyle(color: '#31748f'),
  'attr': HljsStyle(color: '#c4a7e7'),
  'attribute': HljsStyle(color: '#f6c177'),
  'built_in': HljsStyle(color: '#f6c177'),
  'bullet': HljsStyle(color: '#31748f'),
  'char.escape': HljsStyle(color: '#c4a7e7'),
  'code': HljsStyle(color: '#ebbcba'),
  'comment': HljsStyle(color: '#6e6a86'),
  'deletion': HljsStyle(color: '#eb6f92'),
  'doctag': HljsStyle(color: '#eb6f92'),
  'emphasis': HljsStyle(italic: true),
  'formula': HljsStyle(color: '#ebbcba'),
  'keyword': HljsStyle(color: '#c4a7e7'),
  'link': HljsStyle(color: '#ebbcba'),
  'literal': HljsStyle(color: '#ebbcba'),
  'meta': HljsStyle(color: '#6e6a86'),
  'name': HljsStyle(color: '#c4a7e7'),
  'number': HljsStyle(color: '#ebbcba'),
  'operator': HljsStyle(color: '#c4a7e7'),
  'params': HljsStyle(color: '#ebbcba'),
  'property': HljsStyle(color: '#9ccfd8'),
  'punctuation': HljsStyle(color: '#e0def4'),
  'quote': HljsStyle(color: '#31748f'),
  'regexp': HljsStyle(color: '#eb6f92'),
  'section': HljsStyle(color: '#ebbcba'),
  'selector-attr': HljsStyle(color: '#eb6f92'),
  'selector-class': HljsStyle(color: '#eb6f92'),
  'selector-id': HljsStyle(color: '#eb6f92'),
  'selector-pseudo': HljsStyle(color: '#eb6f92'),
  'selector-tag': HljsStyle(color: '#9ccfd8'),
  'string': HljsStyle(color: '#31748f'),
  'strong': HljsStyle(bold: true),
  'subst': HljsStyle(color: '#9ccfd8'),
  'symbol': HljsStyle(color: '#31748f'),
  'tag': HljsStyle(color: '#eb6f92'),
  'template-tag': HljsStyle(color: '#eb6f92'),
  'template-variable': HljsStyle(color: '#ebbcba'),
  'title': HljsStyle(color: '#9ccfd8'),
  'title.class': HljsStyle(color: '#9ccfd8'),
  'title.class.inherited': HljsStyle(color: '#9ccfd8'),
  'title.function': HljsStyle(color: '#9ccfd8'),
  'type': HljsStyle(color: '#ebbcba'),
  'variable': HljsStyle(color: '#ebbcba'),
  'variable.language': HljsStyle(color: '#eb6f92'),
};
