// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `rose-pine-dawn` theme.
const rosePineDawnTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#575279', backgroundColor: '#faf4ed'),
  'addition': HljsStyle(color: '#286983'),
  'attr': HljsStyle(color: '#907aa9'),
  'attribute': HljsStyle(color: '#ea9d34'),
  'built_in': HljsStyle(color: '#ea9d34'),
  'bullet': HljsStyle(color: '#286983'),
  'char.escape': HljsStyle(color: '#907aa9'),
  'code': HljsStyle(color: '#d7827e'),
  'comment': HljsStyle(color: '#9893a5'),
  'deletion': HljsStyle(color: '#b4637a'),
  'doctag': HljsStyle(color: '#b4637a'),
  'emphasis': HljsStyle(italic: true),
  'formula': HljsStyle(color: '#d7827e'),
  'keyword': HljsStyle(color: '#907aa9'),
  'link': HljsStyle(color: '#d7827e'),
  'literal': HljsStyle(color: '#d7827e'),
  'meta': HljsStyle(color: '#9893a5'),
  'name': HljsStyle(color: '#907aa9'),
  'number': HljsStyle(color: '#d7827e'),
  'operator': HljsStyle(color: '#907aa9'),
  'params': HljsStyle(color: '#d7827e'),
  'property': HljsStyle(color: '#56949f'),
  'punctuation': HljsStyle(color: '#575279'),
  'quote': HljsStyle(color: '#286983'),
  'regexp': HljsStyle(color: '#b4637a'),
  'section': HljsStyle(color: '#d7827e'),
  'selector-attr': HljsStyle(color: '#b4637a'),
  'selector-class': HljsStyle(color: '#b4637a'),
  'selector-id': HljsStyle(color: '#b4637a'),
  'selector-pseudo': HljsStyle(color: '#b4637a'),
  'selector-tag': HljsStyle(color: '#56949f'),
  'string': HljsStyle(color: '#286983'),
  'strong': HljsStyle(bold: true),
  'subst': HljsStyle(color: '#56949f'),
  'symbol': HljsStyle(color: '#286983'),
  'tag': HljsStyle(color: '#b4637a'),
  'template-tag': HljsStyle(color: '#b4637a'),
  'template-variable': HljsStyle(color: '#d7827e'),
  'title': HljsStyle(color: '#56949f'),
  'title.class': HljsStyle(color: '#56949f'),
  'title.class.inherited': HljsStyle(color: '#56949f'),
  'title.function': HljsStyle(color: '#56949f'),
  'type': HljsStyle(color: '#d7827e'),
  'variable': HljsStyle(color: '#d7827e'),
  'variable.language': HljsStyle(color: '#b4637a'),
};
