// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `tokyo-night-dark` theme.
const tokyoNightDarkTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#9aa5ce', backgroundColor: '#1a1b26'),
  'addition': HljsStyle(color: '#9ece6a'),
  'attr': HljsStyle(color: '#bb9af7'),
  'attribute': HljsStyle(color: '#e0af68'),
  'built_in': HljsStyle(color: '#e0af68'),
  'bullet': HljsStyle(color: '#9ece6a'),
  'char.escape': HljsStyle(color: '#bb9af7'),
  'code': HljsStyle(color: '#7aa2f7'),
  'comment': HljsStyle(color: '#565f89'),
  'deletion': HljsStyle(color: '#f7768e'),
  'doctag': HljsStyle(color: '#f7768e'),
  'emphasis': HljsStyle(italic: true),
  'formula': HljsStyle(color: '#7aa2f7'),
  'keyword': HljsStyle(color: '#bb9af7'),
  'link': HljsStyle(color: '#ff9e64'),
  'literal': HljsStyle(color: '#ff9e64'),
  'meta': HljsStyle(color: '#565f89'),
  'name': HljsStyle(color: '#bb9af7'),
  'number': HljsStyle(color: '#ff9e64'),
  'operator': HljsStyle(color: '#bb9af7'),
  'params': HljsStyle(color: '#ff9e64'),
  'property': HljsStyle(color: '#7dcfff'),
  'punctuation': HljsStyle(color: '#c0caf5'),
  'quote': HljsStyle(color: '#9ece6a'),
  'regexp': HljsStyle(color: '#f7768e'),
  'section': HljsStyle(color: '#7aa2f7'),
  'selector-attr': HljsStyle(color: '#f7768e'),
  'selector-class': HljsStyle(color: '#f7768e'),
  'selector-id': HljsStyle(color: '#f7768e'),
  'selector-pseudo': HljsStyle(color: '#f7768e'),
  'selector-tag': HljsStyle(color: '#73daca'),
  'string': HljsStyle(color: '#9ece6a'),
  'strong': HljsStyle(bold: true),
  'subst': HljsStyle(color: '#7dcfff'),
  'symbol': HljsStyle(color: '#9ece6a'),
  'tag': HljsStyle(color: '#f7768e'),
  'template-tag': HljsStyle(color: '#f7768e'),
  'template-variable': HljsStyle(color: '#ff9e64'),
  'title': HljsStyle(color: '#7dcfff'),
  'title.class': HljsStyle(color: '#7dcfff'),
  'title.class.inherited': HljsStyle(color: '#7dcfff'),
  'title.function': HljsStyle(color: '#7dcfff'),
  'type': HljsStyle(color: '#ff9e64'),
  'variable': HljsStyle(color: '#ff9e64'),
  'variable.language': HljsStyle(color: '#f7768e'),
};
