// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `tokyo-night-light` theme.
const tokyoNightLightTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#565a6e', backgroundColor: '#d5d6db'),
  'addition': HljsStyle(color: '#485e30'),
  'attr': HljsStyle(color: '#5a4a78'),
  'attribute': HljsStyle(color: '#8f5e15'),
  'built_in': HljsStyle(color: '#8f5e15'),
  'bullet': HljsStyle(color: '#485e30'),
  'char.escape': HljsStyle(color: '#5a4a78'),
  'code': HljsStyle(color: '#34548a'),
  'comment': HljsStyle(color: '#9699a3'),
  'deletion': HljsStyle(color: '#8c4351'),
  'doctag': HljsStyle(color: '#8c4351'),
  'emphasis': HljsStyle(italic: true),
  'formula': HljsStyle(color: '#34548a'),
  'keyword': HljsStyle(color: '#5a4a78'),
  'link': HljsStyle(color: '#965027'),
  'literal': HljsStyle(color: '#965027'),
  'meta': HljsStyle(color: '#9699a3'),
  'name': HljsStyle(color: '#5a4a78'),
  'number': HljsStyle(color: '#965027'),
  'operator': HljsStyle(color: '#5a4a78'),
  'params': HljsStyle(color: '#965027'),
  'property': HljsStyle(color: '#0f4b6e'),
  'punctuation': HljsStyle(color: '#343b58'),
  'quote': HljsStyle(color: '#485e30'),
  'regexp': HljsStyle(color: '#8c4351'),
  'section': HljsStyle(color: '#34548a'),
  'selector-attr': HljsStyle(color: '#8c4351'),
  'selector-class': HljsStyle(color: '#8c4351'),
  'selector-id': HljsStyle(color: '#8c4351'),
  'selector-pseudo': HljsStyle(color: '#8c4351'),
  'selector-tag': HljsStyle(color: '#33635c'),
  'string': HljsStyle(color: '#485e30'),
  'strong': HljsStyle(bold: true),
  'subst': HljsStyle(color: '#0f4b6e'),
  'symbol': HljsStyle(color: '#485e30'),
  'tag': HljsStyle(color: '#8c4351'),
  'template-tag': HljsStyle(color: '#8c4351'),
  'template-variable': HljsStyle(color: '#965027'),
  'title': HljsStyle(color: '#0f4b6e'),
  'title.class': HljsStyle(color: '#0f4b6e'),
  'title.class.inherited': HljsStyle(color: '#0f4b6e'),
  'title.function': HljsStyle(color: '#0f4b6e'),
  'type': HljsStyle(color: '#965027'),
  'variable': HljsStyle(color: '#965027'),
  'variable.language': HljsStyle(color: '#8c4351'),
};
