import 'package:highlight/highlight_core.dart' show HljsStyle;

const vsDarkTheme = <String, HljsStyle>{
  'root': const HljsStyle(color: '#cccccc', backgroundColor: '#202020'),
  'addition': const HljsStyle(color: '#ce9178'),
  'attr': const HljsStyle(color: '#9ddcfe'),
  'attribute': const HljsStyle(color: '#ce9178'),
  'built_in': const HljsStyle(color: '#579cd6'),
  'bullet': const HljsStyle(color: '#00b0e8'),
  'comment': const HljsStyle(color: '#6a9954'),
  'deletion': const HljsStyle(color: '#d4d4d4'),
  'doctag': const HljsStyle(color: '#6a9954'),
  'emphasis': const HljsStyle(italic: true),
  'keyword': const HljsStyle(color: '#579cd6'),
  'link': const HljsStyle(color: '#00b0e8'),
  'literal': const HljsStyle(color: '#ce9178'),
  'meta': const HljsStyle(color: '#d4d4d4'),
  'name': const HljsStyle(color: '#579cd6'),
  'quote': const HljsStyle(color: '#6a9954'),
  'section': const HljsStyle(color: '#ce9178'),
  'selector-attr': const HljsStyle(color: '#d4d4d4'),
  'selector-pseudo': const HljsStyle(color: '#d4d4d4'),
  'selector-tag': const HljsStyle(color: '#579cd6'),
  'string': const HljsStyle(color: '#ce9178'),
  'strong': const HljsStyle(bold: true),
  'symbol': const HljsStyle(color: '#00b0e8'),
  'tag': const HljsStyle(color: '#579cd6'),
  'template-tag': const HljsStyle(color: '#ce9178'),
  'template-variable': const HljsStyle(color: '#ce9178'),
  'title': const HljsStyle(color: '#ce9178'),
  'type': const HljsStyle(color: '#ce9178'),
  'variable': const HljsStyle(color: '#6a9954'),
};
