// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/atelier-seaside-light` theme.
const base16AtelierSeasideLightTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#5e6e5e', backgroundColor: '#f4fbf4'),
  'addition': HljsStyle(color: '#29a329'),
  'attr': HljsStyle(color: '#87711d'),
  'attribute': HljsStyle(color: '#3d62f5'),
  'built_in': HljsStyle(color: '#1999b3'),
  'bullet': HljsStyle(color: '#e6193c'),
  'code': HljsStyle(color: '#29a329'),
  'comment': HljsStyle(color: '#809980'),
  'deletion': HljsStyle(color: '#e6193c'),
  'doctag': HljsStyle(color: '#1999b3'),
  'emphasis': HljsStyle(color: '#ad2bee', italic: true),
  'keyword': HljsStyle(color: '#ad2bee'),
  'link': HljsStyle(color: '#87711d'),
  'literal': HljsStyle(color: '#87711d'),
  'meta': HljsStyle(color: '#e619c3'),
  'meta keyword': HljsStyle(color: '#e619c3', bold: true),
  'meta string': HljsStyle(color: '#e619c3'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#e6193c'),
  'number': HljsStyle(color: '#87711d'),
  'operator': HljsStyle(color: '#5e6e5e'),
  'punctuation': HljsStyle(color: '#5e6e5e'),
  'quote': HljsStyle(color: '#1999b3'),
  'regexp': HljsStyle(color: '#1999b3'),
  'section': HljsStyle(color: '#3d62f5'),
  'selector-tag': HljsStyle(color: '#e6193c'),
  'string': HljsStyle(color: '#29a329'),
  'strong': HljsStyle(color: '#98981b', bold: true),
  'subst': HljsStyle(color: '#5e6e5e'),
  'symbol': HljsStyle(color: '#87711d'),
  'tag': HljsStyle(color: '#687d68'),
  'template-tag': HljsStyle(color: '#ad2bee'),
  'template-variable': HljsStyle(color: '#e6193c'),
  'title': HljsStyle(color: '#98981b'),
  'title.class': HljsStyle(color: '#98981b'),
  'title.class.inherited': HljsStyle(color: '#29a329'),
  'title.function': HljsStyle(color: '#3d62f5'),
  'type': HljsStyle(color: '#ad2bee'),
  'variable': HljsStyle(color: '#e6193c'),
  'variable.constant': HljsStyle(color: '#87711d'),
};
