// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/atelier-cave-light` theme.
const base16AtelierCaveLightTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#585260', backgroundColor: '#efecf4'),
  'addition': HljsStyle(color: '#2a9292'),
  'attr': HljsStyle(color: '#aa573c'),
  'attribute': HljsStyle(color: '#576ddb'),
  'built_in': HljsStyle(color: '#398bc6'),
  'bullet': HljsStyle(color: '#be4678'),
  'code': HljsStyle(color: '#2a9292'),
  'comment': HljsStyle(color: '#7e7887'),
  'deletion': HljsStyle(color: '#be4678'),
  'doctag': HljsStyle(color: '#398bc6'),
  'emphasis': HljsStyle(color: '#955ae7', italic: true),
  'keyword': HljsStyle(color: '#955ae7'),
  'link': HljsStyle(color: '#aa573c'),
  'literal': HljsStyle(color: '#aa573c'),
  'meta': HljsStyle(color: '#bf40bf'),
  'meta keyword': HljsStyle(color: '#bf40bf', bold: true),
  'meta string': HljsStyle(color: '#bf40bf'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#be4678'),
  'number': HljsStyle(color: '#aa573c'),
  'operator': HljsStyle(color: '#585260'),
  'punctuation': HljsStyle(color: '#585260'),
  'quote': HljsStyle(color: '#398bc6'),
  'regexp': HljsStyle(color: '#398bc6'),
  'section': HljsStyle(color: '#576ddb'),
  'selector-tag': HljsStyle(color: '#be4678'),
  'string': HljsStyle(color: '#2a9292'),
  'strong': HljsStyle(color: '#a06e3b', bold: true),
  'subst': HljsStyle(color: '#585260'),
  'symbol': HljsStyle(color: '#aa573c'),
  'tag': HljsStyle(color: '#655f6d'),
  'template-tag': HljsStyle(color: '#955ae7'),
  'template-variable': HljsStyle(color: '#be4678'),
  'title': HljsStyle(color: '#a06e3b'),
  'title.class': HljsStyle(color: '#a06e3b'),
  'title.class.inherited': HljsStyle(color: '#2a9292'),
  'title.function': HljsStyle(color: '#576ddb'),
  'type': HljsStyle(color: '#955ae7'),
  'variable': HljsStyle(color: '#be4678'),
  'variable.constant': HljsStyle(color: '#aa573c'),
};
