// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/bespin` theme.
const base16BespinTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#8a8986', backgroundColor: '#28211c'),
  'addition': HljsStyle(color: '#54be0d'),
  'attr': HljsStyle(color: '#cf7d34'),
  'attribute': HljsStyle(color: '#5ea6ea'),
  'built_in': HljsStyle(color: '#afc4db'),
  'bullet': HljsStyle(color: '#cf6a4c'),
  'code': HljsStyle(color: '#54be0d'),
  'comment': HljsStyle(color: '#666666'),
  'deletion': HljsStyle(color: '#cf6a4c'),
  'doctag': HljsStyle(color: '#afc4db'),
  'emphasis': HljsStyle(color: '#9b859d', italic: true),
  'keyword': HljsStyle(color: '#9b859d'),
  'link': HljsStyle(color: '#cf7d34'),
  'literal': HljsStyle(color: '#cf7d34'),
  'meta': HljsStyle(color: '#937121'),
  'meta keyword': HljsStyle(color: '#937121', bold: true),
  'meta string': HljsStyle(color: '#937121'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#cf6a4c'),
  'number': HljsStyle(color: '#cf7d34'),
  'operator': HljsStyle(color: '#8a8986'),
  'punctuation': HljsStyle(color: '#8a8986'),
  'quote': HljsStyle(color: '#afc4db'),
  'regexp': HljsStyle(color: '#afc4db'),
  'section': HljsStyle(color: '#5ea6ea'),
  'selector-tag': HljsStyle(color: '#cf6a4c'),
  'string': HljsStyle(color: '#54be0d'),
  'strong': HljsStyle(color: '#f9ee98', bold: true),
  'subst': HljsStyle(color: '#8a8986'),
  'symbol': HljsStyle(color: '#cf7d34'),
  'tag': HljsStyle(color: '#797977'),
  'template-tag': HljsStyle(color: '#9b859d'),
  'template-variable': HljsStyle(color: '#cf6a4c'),
  'title': HljsStyle(color: '#f9ee98'),
  'title.class': HljsStyle(color: '#f9ee98'),
  'title.class.inherited': HljsStyle(color: '#54be0d'),
  'title.function': HljsStyle(color: '#5ea6ea'),
  'type': HljsStyle(color: '#9b859d'),
  'variable': HljsStyle(color: '#cf6a4c'),
  'variable.constant': HljsStyle(color: '#cf7d34'),
};
