// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/brogrammer` theme.
const base16BrogrammerTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#4e5ab7', backgroundColor: '#1f1f1f'),
  'addition': HljsStyle(color: '#f3bd09'),
  'attr': HljsStyle(color: '#de352e'),
  'attribute': HljsStyle(color: '#5350b9'),
  'built_in': HljsStyle(color: '#1081d6'),
  'bullet': HljsStyle(color: '#d6dbe5'),
  'code': HljsStyle(color: '#f3bd09'),
  'comment': HljsStyle(color: '#ecba0f'),
  'deletion': HljsStyle(color: '#d6dbe5'),
  'doctag': HljsStyle(color: '#1081d6'),
  'emphasis': HljsStyle(color: '#0f7ddb', italic: true),
  'keyword': HljsStyle(color: '#0f7ddb'),
  'link': HljsStyle(color: '#de352e'),
  'literal': HljsStyle(color: '#de352e'),
  'meta': HljsStyle(color: '#ffffff'),
  'meta keyword': HljsStyle(color: '#ffffff', bold: true),
  'meta string': HljsStyle(color: '#ffffff'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#d6dbe5'),
  'number': HljsStyle(color: '#de352e'),
  'operator': HljsStyle(color: '#4e5ab7'),
  'punctuation': HljsStyle(color: '#4e5ab7'),
  'quote': HljsStyle(color: '#1081d6'),
  'regexp': HljsStyle(color: '#1081d6'),
  'section': HljsStyle(color: '#5350b9'),
  'selector-tag': HljsStyle(color: '#d6dbe5'),
  'string': HljsStyle(color: '#f3bd09'),
  'strong': HljsStyle(color: '#1dd361', bold: true),
  'subst': HljsStyle(color: '#4e5ab7'),
  'symbol': HljsStyle(color: '#de352e'),
  'tag': HljsStyle(color: '#2a84d2'),
  'template-tag': HljsStyle(color: '#0f7ddb'),
  'template-variable': HljsStyle(color: '#d6dbe5'),
  'title': HljsStyle(color: '#1dd361'),
  'title.class': HljsStyle(color: '#1dd361'),
  'title.class.inherited': HljsStyle(color: '#f3bd09'),
  'title.function': HljsStyle(color: '#5350b9'),
  'type': HljsStyle(color: '#0f7ddb'),
  'variable': HljsStyle(color: '#d6dbe5'),
  'variable.constant': HljsStyle(color: '#de352e'),
};
