// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/circus` theme.
const base16CircusTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#a7a7a7', backgroundColor: '#191919'),
  'addition': HljsStyle(color: '#84b97c'),
  'attr': HljsStyle(color: '#4bb1a7'),
  'attribute': HljsStyle(color: '#639ee4'),
  'built_in': HljsStyle(color: '#4bb1a7'),
  'bullet': HljsStyle(color: '#dc657d'),
  'code': HljsStyle(color: '#84b97c'),
  'comment': HljsStyle(color: '#5f5a60'),
  'deletion': HljsStyle(color: '#dc657d'),
  'doctag': HljsStyle(color: '#4bb1a7'),
  'emphasis': HljsStyle(color: '#b888e2', italic: true),
  'keyword': HljsStyle(color: '#b888e2'),
  'link': HljsStyle(color: '#4bb1a7'),
  'literal': HljsStyle(color: '#4bb1a7'),
  'meta': HljsStyle(color: '#b888e2'),
  'meta keyword': HljsStyle(color: '#b888e2', bold: true),
  'meta string': HljsStyle(color: '#b888e2'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#dc657d'),
  'number': HljsStyle(color: '#4bb1a7'),
  'operator': HljsStyle(color: '#a7a7a7'),
  'punctuation': HljsStyle(color: '#a7a7a7'),
  'quote': HljsStyle(color: '#4bb1a7'),
  'regexp': HljsStyle(color: '#4bb1a7'),
  'section': HljsStyle(color: '#639ee4'),
  'selector-tag': HljsStyle(color: '#dc657d'),
  'string': HljsStyle(color: '#84b97c'),
  'strong': HljsStyle(color: '#c3ba63', bold: true),
  'subst': HljsStyle(color: '#a7a7a7'),
  'symbol': HljsStyle(color: '#4bb1a7'),
  'tag': HljsStyle(color: '#505050'),
  'template-tag': HljsStyle(color: '#b888e2'),
  'template-variable': HljsStyle(color: '#dc657d'),
  'title': HljsStyle(color: '#c3ba63'),
  'title.class': HljsStyle(color: '#c3ba63'),
  'title.class.inherited': HljsStyle(color: '#84b97c'),
  'title.function': HljsStyle(color: '#639ee4'),
  'type': HljsStyle(color: '#b888e2'),
  'variable': HljsStyle(color: '#dc657d'),
  'variable.constant': HljsStyle(color: '#4bb1a7'),
};
