// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/dark-violet` theme.
const base16DarkVioletTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#b08ae6', backgroundColor: '#000000'),
  'addition': HljsStyle(color: '#4595e6'),
  'attr': HljsStyle(color: '#bb66cc'),
  'attribute': HljsStyle(color: '#4136d9'),
  'built_in': HljsStyle(color: '#40dfff'),
  'bullet': HljsStyle(color: '#a82ee6'),
  'code': HljsStyle(color: '#4595e6'),
  'comment': HljsStyle(color: '#593380'),
  'deletion': HljsStyle(color: '#a82ee6'),
  'doctag': HljsStyle(color: '#40dfff'),
  'emphasis': HljsStyle(color: '#7e5ce6', italic: true),
  'keyword': HljsStyle(color: '#7e5ce6'),
  'link': HljsStyle(color: '#bb66cc'),
  'literal': HljsStyle(color: '#bb66cc'),
  'meta': HljsStyle(color: '#a886bf'),
  'meta keyword': HljsStyle(color: '#a886bf', bold: true),
  'meta string': HljsStyle(color: '#a886bf'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#a82ee6'),
  'number': HljsStyle(color: '#bb66cc'),
  'operator': HljsStyle(color: '#b08ae6'),
  'punctuation': HljsStyle(color: '#b08ae6'),
  'quote': HljsStyle(color: '#40dfff'),
  'regexp': HljsStyle(color: '#40dfff'),
  'section': HljsStyle(color: '#4136d9'),
  'selector-tag': HljsStyle(color: '#a82ee6'),
  'string': HljsStyle(color: '#4595e6'),
  'strong': HljsStyle(color: '#f29df2', bold: true),
  'subst': HljsStyle(color: '#b08ae6'),
  'symbol': HljsStyle(color: '#bb66cc'),
  'tag': HljsStyle(color: '#00ff00'),
  'template-tag': HljsStyle(color: '#7e5ce6'),
  'template-variable': HljsStyle(color: '#a82ee6'),
  'title': HljsStyle(color: '#f29df2'),
  'title.class': HljsStyle(color: '#f29df2'),
  'title.class.inherited': HljsStyle(color: '#4595e6'),
  'title.function': HljsStyle(color: '#4136d9'),
  'type': HljsStyle(color: '#7e5ce6'),
  'variable': HljsStyle(color: '#a82ee6'),
  'variable.constant': HljsStyle(color: '#bb66cc'),
};
