// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/eva` theme.
const base16EvaTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#9fa2a6', backgroundColor: '#2a3b4d'),
  'addition': HljsStyle(color: '#66ff66'),
  'attr': HljsStyle(color: '#ff9966'),
  'attribute': HljsStyle(color: '#15f4ee'),
  'built_in': HljsStyle(color: '#4b8f77'),
  'bullet': HljsStyle(color: '#c4676c'),
  'code': HljsStyle(color: '#66ff66'),
  'comment': HljsStyle(color: '#55799c'),
  'deletion': HljsStyle(color: '#c4676c'),
  'doctag': HljsStyle(color: '#4b8f77'),
  'emphasis': HljsStyle(color: '#9c6cd3', italic: true),
  'keyword': HljsStyle(color: '#9c6cd3'),
  'link': HljsStyle(color: '#ff9966'),
  'literal': HljsStyle(color: '#ff9966'),
  'meta': HljsStyle(color: '#bb64a9'),
  'meta keyword': HljsStyle(color: '#bb64a9', bold: true),
  'meta string': HljsStyle(color: '#bb64a9'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#c4676c'),
  'number': HljsStyle(color: '#ff9966'),
  'operator': HljsStyle(color: '#9fa2a6'),
  'punctuation': HljsStyle(color: '#9fa2a6'),
  'quote': HljsStyle(color: '#4b8f77'),
  'regexp': HljsStyle(color: '#4b8f77'),
  'section': HljsStyle(color: '#15f4ee'),
  'selector-tag': HljsStyle(color: '#c4676c'),
  'string': HljsStyle(color: '#66ff66'),
  'strong': HljsStyle(color: '#ffff66', bold: true),
  'subst': HljsStyle(color: '#9fa2a6'),
  'symbol': HljsStyle(color: '#ff9966'),
  'tag': HljsStyle(color: '#7e90a3'),
  'template-tag': HljsStyle(color: '#9c6cd3'),
  'template-variable': HljsStyle(color: '#c4676c'),
  'title': HljsStyle(color: '#ffff66'),
  'title.class': HljsStyle(color: '#ffff66'),
  'title.class.inherited': HljsStyle(color: '#66ff66'),
  'title.function': HljsStyle(color: '#15f4ee'),
  'type': HljsStyle(color: '#9c6cd3'),
  'variable': HljsStyle(color: '#c4676c'),
  'variable.constant': HljsStyle(color: '#ff9966'),
};
