// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/framer` theme.
const base16FramerTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#d0d0d0', backgroundColor: '#181818'),
  'addition': HljsStyle(color: '#32ccdc'),
  'attr': HljsStyle(color: '#fc4769'),
  'attribute': HljsStyle(color: '#20bcfc'),
  'built_in': HljsStyle(color: '#acddfd'),
  'bullet': HljsStyle(color: '#fd886b'),
  'code': HljsStyle(color: '#32ccdc'),
  'comment': HljsStyle(color: '#747474'),
  'deletion': HljsStyle(color: '#fd886b'),
  'doctag': HljsStyle(color: '#acddfd'),
  'emphasis': HljsStyle(color: '#ba8cfc', italic: true),
  'keyword': HljsStyle(color: '#ba8cfc'),
  'link': HljsStyle(color: '#fc4769'),
  'literal': HljsStyle(color: '#fc4769'),
  'meta': HljsStyle(color: '#b15f4a'),
  'meta keyword': HljsStyle(color: '#b15f4a', bold: true),
  'meta string': HljsStyle(color: '#b15f4a'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#fd886b'),
  'number': HljsStyle(color: '#fc4769'),
  'operator': HljsStyle(color: '#d0d0d0'),
  'punctuation': HljsStyle(color: '#d0d0d0'),
  'quote': HljsStyle(color: '#acddfd'),
  'regexp': HljsStyle(color: '#acddfd'),
  'section': HljsStyle(color: '#20bcfc'),
  'selector-tag': HljsStyle(color: '#fd886b'),
  'string': HljsStyle(color: '#32ccdc'),
  'strong': HljsStyle(color: '#fecb6e', bold: true),
  'subst': HljsStyle(color: '#d0d0d0'),
  'symbol': HljsStyle(color: '#fc4769'),
  'tag': HljsStyle(color: '#b9b9b9'),
  'template-tag': HljsStyle(color: '#ba8cfc'),
  'template-variable': HljsStyle(color: '#fd886b'),
  'title': HljsStyle(color: '#fecb6e'),
  'title.class': HljsStyle(color: '#fecb6e'),
  'title.class.inherited': HljsStyle(color: '#32ccdc'),
  'title.function': HljsStyle(color: '#20bcfc'),
  'type': HljsStyle(color: '#ba8cfc'),
  'variable': HljsStyle(color: '#fd886b'),
  'variable.constant': HljsStyle(color: '#fc4769'),
};
