// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/hardcore` theme.
const base16HardcoreTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#cdcdcd', backgroundColor: '#212121'),
  'addition': HljsStyle(color: '#a6e22e'),
  'attr': HljsStyle(color: '#fd971f'),
  'attribute': HljsStyle(color: '#66d9ef'),
  'built_in': HljsStyle(color: '#708387'),
  'bullet': HljsStyle(color: '#f92672'),
  'code': HljsStyle(color: '#a6e22e'),
  'comment': HljsStyle(color: '#4a4a4a'),
  'deletion': HljsStyle(color: '#f92672'),
  'doctag': HljsStyle(color: '#708387'),
  'emphasis': HljsStyle(color: '#9e6ffe', italic: true),
  'keyword': HljsStyle(color: '#9e6ffe'),
  'link': HljsStyle(color: '#fd971f'),
  'literal': HljsStyle(color: '#fd971f'),
  'meta': HljsStyle(color: '#e8b882'),
  'meta keyword': HljsStyle(color: '#e8b882', bold: true),
  'meta string': HljsStyle(color: '#e8b882'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#f92672'),
  'number': HljsStyle(color: '#fd971f'),
  'operator': HljsStyle(color: '#cdcdcd'),
  'punctuation': HljsStyle(color: '#cdcdcd'),
  'quote': HljsStyle(color: '#708387'),
  'regexp': HljsStyle(color: '#708387'),
  'section': HljsStyle(color: '#66d9ef'),
  'selector-tag': HljsStyle(color: '#f92672'),
  'string': HljsStyle(color: '#a6e22e'),
  'strong': HljsStyle(color: '#e6db74', bold: true),
  'subst': HljsStyle(color: '#cdcdcd'),
  'symbol': HljsStyle(color: '#fd971f'),
  'tag': HljsStyle(color: '#707070'),
  'template-tag': HljsStyle(color: '#9e6ffe'),
  'template-variable': HljsStyle(color: '#f92672'),
  'title': HljsStyle(color: '#e6db74'),
  'title.class': HljsStyle(color: '#e6db74'),
  'title.class.inherited': HljsStyle(color: '#a6e22e'),
  'title.function': HljsStyle(color: '#66d9ef'),
  'type': HljsStyle(color: '#9e6ffe'),
  'variable': HljsStyle(color: '#f92672'),
  'variable.constant': HljsStyle(color: '#fd971f'),
};
