// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/heetch-light` theme.
const base16HeetchLightTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#5a496e', backgroundColor: '#feffff'),
  'addition': HljsStyle(color: '#f80059'),
  'attr': HljsStyle(color: '#bdb6c5'),
  'attribute': HljsStyle(color: '#47f9f5'),
  'built_in': HljsStyle(color: '#c33678'),
  'bullet': HljsStyle(color: '#27d9d5'),
  'code': HljsStyle(color: '#f80059'),
  'comment': HljsStyle(color: '#9c92a8'),
  'deletion': HljsStyle(color: '#27d9d5'),
  'doctag': HljsStyle(color: '#c33678'),
  'emphasis': HljsStyle(color: '#bd0152', italic: true),
  'keyword': HljsStyle(color: '#bd0152'),
  'link': HljsStyle(color: '#bdb6c5'),
  'literal': HljsStyle(color: '#bdb6c5'),
  'meta': HljsStyle(color: '#dedae2'),
  'meta keyword': HljsStyle(color: '#dedae2', bold: true),
  'meta string': HljsStyle(color: '#dedae2'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#27d9d5'),
  'number': HljsStyle(color: '#bdb6c5'),
  'operator': HljsStyle(color: '#5a496e'),
  'punctuation': HljsStyle(color: '#5a496e'),
  'quote': HljsStyle(color: '#c33678'),
  'regexp': HljsStyle(color: '#c33678'),
  'section': HljsStyle(color: '#47f9f5'),
  'selector-tag': HljsStyle(color: '#27d9d5'),
  'string': HljsStyle(color: '#f80059'),
  'strong': HljsStyle(color: '#5ba2b6', bold: true),
  'subst': HljsStyle(color: '#5a496e'),
  'symbol': HljsStyle(color: '#bdb6c5'),
  'tag': HljsStyle(color: '#ddd6e5'),
  'template-tag': HljsStyle(color: '#bd0152'),
  'template-variable': HljsStyle(color: '#27d9d5'),
  'title': HljsStyle(color: '#5ba2b6'),
  'title.class': HljsStyle(color: '#5ba2b6'),
  'title.class.inherited': HljsStyle(color: '#f80059'),
  'title.function': HljsStyle(color: '#47f9f5'),
  'type': HljsStyle(color: '#bd0152'),
  'variable': HljsStyle(color: '#27d9d5'),
  'variable.constant': HljsStyle(color: '#bdb6c5'),
};
