// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/helios` theme.
const base16HeliosTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#d5d5d5', backgroundColor: '#1d2021'),
  'addition': HljsStyle(color: '#88b92d'),
  'attr': HljsStyle(color: '#eb8413'),
  'attribute': HljsStyle(color: '#1e8bac'),
  'built_in': HljsStyle(color: '#1ba595'),
  'bullet': HljsStyle(color: '#d72638'),
  'code': HljsStyle(color: '#88b92d'),
  'comment': HljsStyle(color: '#6f7579'),
  'deletion': HljsStyle(color: '#d72638'),
  'doctag': HljsStyle(color: '#1ba595'),
  'emphasis': HljsStyle(color: '#be4264', italic: true),
  'keyword': HljsStyle(color: '#be4264'),
  'link': HljsStyle(color: '#eb8413'),
  'literal': HljsStyle(color: '#eb8413'),
  'meta': HljsStyle(color: '#c85e0d'),
  'meta keyword': HljsStyle(color: '#c85e0d', bold: true),
  'meta string': HljsStyle(color: '#c85e0d'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#d72638'),
  'number': HljsStyle(color: '#eb8413'),
  'operator': HljsStyle(color: '#d5d5d5'),
  'punctuation': HljsStyle(color: '#d5d5d5'),
  'quote': HljsStyle(color: '#1ba595'),
  'regexp': HljsStyle(color: '#1ba595'),
  'section': HljsStyle(color: '#1e8bac'),
  'selector-tag': HljsStyle(color: '#d72638'),
  'string': HljsStyle(color: '#88b92d'),
  'strong': HljsStyle(color: '#f19d1a', bold: true),
  'subst': HljsStyle(color: '#d5d5d5'),
  'symbol': HljsStyle(color: '#eb8413'),
  'tag': HljsStyle(color: '#cdcdcd'),
  'template-tag': HljsStyle(color: '#be4264'),
  'template-variable': HljsStyle(color: '#d72638'),
  'title': HljsStyle(color: '#f19d1a'),
  'title.class': HljsStyle(color: '#f19d1a'),
  'title.class.inherited': HljsStyle(color: '#88b92d'),
  'title.function': HljsStyle(color: '#1e8bac'),
  'type': HljsStyle(color: '#be4264'),
  'variable': HljsStyle(color: '#d72638'),
  'variable.constant': HljsStyle(color: '#eb8413'),
};
