// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/humanoid-dark` theme.
const base16HumanoidDarkTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#f8f8f2', backgroundColor: '#232629'),
  'addition': HljsStyle(color: '#02d849'),
  'attr': HljsStyle(color: '#ff9505'),
  'attribute': HljsStyle(color: '#00a6fb'),
  'built_in': HljsStyle(color: '#0dd9d6'),
  'bullet': HljsStyle(color: '#f11235'),
  'code': HljsStyle(color: '#02d849'),
  'comment': HljsStyle(color: '#60615d'),
  'deletion': HljsStyle(color: '#f11235'),
  'doctag': HljsStyle(color: '#0dd9d6'),
  'emphasis': HljsStyle(color: '#f15ee3', italic: true),
  'keyword': HljsStyle(color: '#f15ee3'),
  'link': HljsStyle(color: '#ff9505'),
  'literal': HljsStyle(color: '#ff9505'),
  'meta': HljsStyle(color: '#b27701'),
  'meta keyword': HljsStyle(color: '#b27701', bold: true),
  'meta string': HljsStyle(color: '#b27701'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#f11235'),
  'number': HljsStyle(color: '#ff9505'),
  'operator': HljsStyle(color: '#f8f8f2'),
  'punctuation': HljsStyle(color: '#f8f8f2'),
  'quote': HljsStyle(color: '#0dd9d6'),
  'regexp': HljsStyle(color: '#0dd9d6'),
  'section': HljsStyle(color: '#00a6fb'),
  'selector-tag': HljsStyle(color: '#f11235'),
  'string': HljsStyle(color: '#02d849'),
  'strong': HljsStyle(color: '#ffb627', bold: true),
  'subst': HljsStyle(color: '#f8f8f2'),
  'symbol': HljsStyle(color: '#ff9505'),
  'tag': HljsStyle(color: '#c0c0bd'),
  'template-tag': HljsStyle(color: '#f15ee3'),
  'template-variable': HljsStyle(color: '#f11235'),
  'title': HljsStyle(color: '#ffb627'),
  'title.class': HljsStyle(color: '#ffb627'),
  'title.class.inherited': HljsStyle(color: '#02d849'),
  'title.function': HljsStyle(color: '#00a6fb'),
  'type': HljsStyle(color: '#f15ee3'),
  'variable': HljsStyle(color: '#f11235'),
  'variable.constant': HljsStyle(color: '#ff9505'),
};
