// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/ia-light` theme.
const base16IaLightTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#181818', backgroundColor: '#f6f6f6'),
  'addition': HljsStyle(color: '#38781c'),
  'attr': HljsStyle(color: '#c43e18'),
  'attribute': HljsStyle(color: '#48bac2'),
  'built_in': HljsStyle(color: '#2d6bb1'),
  'bullet': HljsStyle(color: '#9c5a02'),
  'code': HljsStyle(color: '#38781c'),
  'comment': HljsStyle(color: '#898989'),
  'deletion': HljsStyle(color: '#9c5a02'),
  'doctag': HljsStyle(color: '#2d6bb1'),
  'emphasis': HljsStyle(color: '#a94598', italic: true),
  'keyword': HljsStyle(color: '#a94598'),
  'link': HljsStyle(color: '#c43e18'),
  'literal': HljsStyle(color: '#c43e18'),
  'meta': HljsStyle(color: '#8b6c37'),
  'meta keyword': HljsStyle(color: '#8b6c37', bold: true),
  'meta string': HljsStyle(color: '#8b6c37'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#9c5a02'),
  'number': HljsStyle(color: '#c43e18'),
  'operator': HljsStyle(color: '#181818'),
  'punctuation': HljsStyle(color: '#181818'),
  'quote': HljsStyle(color: '#2d6bb1'),
  'regexp': HljsStyle(color: '#2d6bb1'),
  'section': HljsStyle(color: '#48bac2'),
  'selector-tag': HljsStyle(color: '#9c5a02'),
  'string': HljsStyle(color: '#38781c'),
  'strong': HljsStyle(color: '#c48218', bold: true),
  'subst': HljsStyle(color: '#181818'),
  'symbol': HljsStyle(color: '#c43e18'),
  'tag': HljsStyle(color: '#767676'),
  'template-tag': HljsStyle(color: '#a94598'),
  'template-variable': HljsStyle(color: '#9c5a02'),
  'title': HljsStyle(color: '#c48218'),
  'title.class': HljsStyle(color: '#c48218'),
  'title.class.inherited': HljsStyle(color: '#38781c'),
  'title.function': HljsStyle(color: '#48bac2'),
  'type': HljsStyle(color: '#a94598'),
  'variable': HljsStyle(color: '#9c5a02'),
  'variable.constant': HljsStyle(color: '#c43e18'),
};
