// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/london-tube` theme.
const base16LondonTubeTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#d9d8d8', backgroundColor: '#231f20'),
  'addition': HljsStyle(color: '#00853e'),
  'attr': HljsStyle(color: '#f386a1'),
  'attribute': HljsStyle(color: '#009ddc'),
  'built_in': HljsStyle(color: '#85cebc'),
  'bullet': HljsStyle(color: '#ee2e24'),
  'code': HljsStyle(color: '#00853e'),
  'comment': HljsStyle(color: '#737171'),
  'deletion': HljsStyle(color: '#ee2e24'),
  'doctag': HljsStyle(color: '#85cebc'),
  'emphasis': HljsStyle(color: '#98005d', italic: true),
  'keyword': HljsStyle(color: '#98005d'),
  'link': HljsStyle(color: '#f386a1'),
  'literal': HljsStyle(color: '#f386a1'),
  'meta': HljsStyle(color: '#b06110'),
  'meta keyword': HljsStyle(color: '#b06110', bold: true),
  'meta string': HljsStyle(color: '#b06110'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#ee2e24'),
  'number': HljsStyle(color: '#f386a1'),
  'operator': HljsStyle(color: '#d9d8d8'),
  'punctuation': HljsStyle(color: '#d9d8d8'),
  'quote': HljsStyle(color: '#85cebc'),
  'regexp': HljsStyle(color: '#85cebc'),
  'section': HljsStyle(color: '#009ddc'),
  'selector-tag': HljsStyle(color: '#ee2e24'),
  'string': HljsStyle(color: '#00853e'),
  'strong': HljsStyle(color: '#ffd204', bold: true),
  'subst': HljsStyle(color: '#d9d8d8'),
  'symbol': HljsStyle(color: '#f386a1'),
  'tag': HljsStyle(color: '#959ca1'),
  'template-tag': HljsStyle(color: '#98005d'),
  'template-variable': HljsStyle(color: '#ee2e24'),
  'title': HljsStyle(color: '#ffd204'),
  'title.class': HljsStyle(color: '#ffd204'),
  'title.class.inherited': HljsStyle(color: '#00853e'),
  'title.function': HljsStyle(color: '#009ddc'),
  'type': HljsStyle(color: '#98005d'),
  'variable': HljsStyle(color: '#ee2e24'),
  'variable.constant': HljsStyle(color: '#f386a1'),
};
