// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/marrakesh` theme.
const base16MarrakeshTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#948e48', backgroundColor: '#201602'),
  'addition': HljsStyle(color: '#18974e'),
  'attr': HljsStyle(color: '#b36144'),
  'attribute': HljsStyle(color: '#477ca1'),
  'built_in': HljsStyle(color: '#75a738'),
  'bullet': HljsStyle(color: '#c35359'),
  'code': HljsStyle(color: '#18974e'),
  'comment': HljsStyle(color: '#6c6823'),
  'deletion': HljsStyle(color: '#c35359'),
  'doctag': HljsStyle(color: '#75a738'),
  'emphasis': HljsStyle(color: '#8868b3', italic: true),
  'keyword': HljsStyle(color: '#8868b3'),
  'link': HljsStyle(color: '#b36144'),
  'literal': HljsStyle(color: '#b36144'),
  'meta': HljsStyle(color: '#b3588e'),
  'meta keyword': HljsStyle(color: '#b3588e', bold: true),
  'meta string': HljsStyle(color: '#b3588e'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#c35359'),
  'number': HljsStyle(color: '#b36144'),
  'operator': HljsStyle(color: '#948e48'),
  'punctuation': HljsStyle(color: '#948e48'),
  'quote': HljsStyle(color: '#75a738'),
  'regexp': HljsStyle(color: '#75a738'),
  'section': HljsStyle(color: '#477ca1'),
  'selector-tag': HljsStyle(color: '#c35359'),
  'string': HljsStyle(color: '#18974e'),
  'strong': HljsStyle(color: '#a88339', bold: true),
  'subst': HljsStyle(color: '#948e48'),
  'symbol': HljsStyle(color: '#b36144'),
  'tag': HljsStyle(color: '#86813b'),
  'template-tag': HljsStyle(color: '#8868b3'),
  'template-variable': HljsStyle(color: '#c35359'),
  'title': HljsStyle(color: '#a88339'),
  'title.class': HljsStyle(color: '#a88339'),
  'title.class.inherited': HljsStyle(color: '#18974e'),
  'title.function': HljsStyle(color: '#477ca1'),
  'type': HljsStyle(color: '#8868b3'),
  'variable': HljsStyle(color: '#c35359'),
  'variable.constant': HljsStyle(color: '#b36144'),
};
