// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/ocean` theme.
const base16OceanTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#c0c5ce', backgroundColor: '#2b303b'),
  'addition': HljsStyle(color: '#a3be8c'),
  'attr': HljsStyle(color: '#d08770'),
  'attribute': HljsStyle(color: '#8fa1b3'),
  'built_in': HljsStyle(color: '#96b5b4'),
  'bullet': HljsStyle(color: '#bf616a'),
  'code': HljsStyle(color: '#a3be8c'),
  'comment': HljsStyle(color: '#65737e'),
  'deletion': HljsStyle(color: '#bf616a'),
  'doctag': HljsStyle(color: '#96b5b4'),
  'emphasis': HljsStyle(color: '#b48ead', italic: true),
  'keyword': HljsStyle(color: '#b48ead'),
  'link': HljsStyle(color: '#d08770'),
  'literal': HljsStyle(color: '#d08770'),
  'meta': HljsStyle(color: '#ab7967'),
  'meta keyword': HljsStyle(color: '#ab7967', bold: true),
  'meta string': HljsStyle(color: '#ab7967'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#bf616a'),
  'number': HljsStyle(color: '#d08770'),
  'operator': HljsStyle(color: '#c0c5ce'),
  'punctuation': HljsStyle(color: '#c0c5ce'),
  'quote': HljsStyle(color: '#96b5b4'),
  'regexp': HljsStyle(color: '#96b5b4'),
  'section': HljsStyle(color: '#8fa1b3'),
  'selector-tag': HljsStyle(color: '#bf616a'),
  'string': HljsStyle(color: '#a3be8c'),
  'strong': HljsStyle(color: '#ebcb8b', bold: true),
  'subst': HljsStyle(color: '#c0c5ce'),
  'symbol': HljsStyle(color: '#d08770'),
  'tag': HljsStyle(color: '#a7adba'),
  'template-tag': HljsStyle(color: '#b48ead'),
  'template-variable': HljsStyle(color: '#bf616a'),
  'title': HljsStyle(color: '#ebcb8b'),
  'title.class': HljsStyle(color: '#ebcb8b'),
  'title.class.inherited': HljsStyle(color: '#a3be8c'),
  'title.function': HljsStyle(color: '#8fa1b3'),
  'type': HljsStyle(color: '#b48ead'),
  'variable': HljsStyle(color: '#bf616a'),
  'variable.constant': HljsStyle(color: '#d08770'),
};
