// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/oceanicnext` theme.
const base16OceanicnextTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#c0c5ce', backgroundColor: '#1b2b34'),
  'addition': HljsStyle(color: '#99c794'),
  'attr': HljsStyle(color: '#f99157'),
  'attribute': HljsStyle(color: '#6699cc'),
  'built_in': HljsStyle(color: '#5fb3b3'),
  'bullet': HljsStyle(color: '#ec5f67'),
  'code': HljsStyle(color: '#99c794'),
  'comment': HljsStyle(color: '#65737e'),
  'deletion': HljsStyle(color: '#ec5f67'),
  'doctag': HljsStyle(color: '#5fb3b3'),
  'emphasis': HljsStyle(color: '#c594c5', italic: true),
  'keyword': HljsStyle(color: '#c594c5'),
  'link': HljsStyle(color: '#f99157'),
  'literal': HljsStyle(color: '#f99157'),
  'meta': HljsStyle(color: '#ab7967'),
  'meta keyword': HljsStyle(color: '#ab7967', bold: true),
  'meta string': HljsStyle(color: '#ab7967'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#ec5f67'),
  'number': HljsStyle(color: '#f99157'),
  'operator': HljsStyle(color: '#c0c5ce'),
  'punctuation': HljsStyle(color: '#c0c5ce'),
  'quote': HljsStyle(color: '#5fb3b3'),
  'regexp': HljsStyle(color: '#5fb3b3'),
  'section': HljsStyle(color: '#6699cc'),
  'selector-tag': HljsStyle(color: '#ec5f67'),
  'string': HljsStyle(color: '#99c794'),
  'strong': HljsStyle(color: '#fac863', bold: true),
  'subst': HljsStyle(color: '#c0c5ce'),
  'symbol': HljsStyle(color: '#f99157'),
  'tag': HljsStyle(color: '#a7adba'),
  'template-tag': HljsStyle(color: '#c594c5'),
  'template-variable': HljsStyle(color: '#ec5f67'),
  'title': HljsStyle(color: '#fac863'),
  'title.class': HljsStyle(color: '#fac863'),
  'title.class.inherited': HljsStyle(color: '#99c794'),
  'title.function': HljsStyle(color: '#6699cc'),
  'type': HljsStyle(color: '#c594c5'),
  'variable': HljsStyle(color: '#ec5f67'),
  'variable.constant': HljsStyle(color: '#f99157'),
};
