// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/ros-pine` theme.
const base16RosPineTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#e0def4', backgroundColor: '#191724'),
  'addition': HljsStyle(color: '#ebbcba'),
  'attr': HljsStyle(color: '#eb6f92'),
  'attribute': HljsStyle(color: '#9ccfd8'),
  'built_in': HljsStyle(color: '#31748f'),
  'bullet': HljsStyle(color: '#e2e1e7'),
  'code': HljsStyle(color: '#ebbcba'),
  'comment': HljsStyle(color: '#555169'),
  'deletion': HljsStyle(color: '#e2e1e7'),
  'doctag': HljsStyle(color: '#31748f'),
  'emphasis': HljsStyle(color: '#c4a7e7', italic: true),
  'keyword': HljsStyle(color: '#c4a7e7'),
  'link': HljsStyle(color: '#eb6f92'),
  'literal': HljsStyle(color: '#eb6f92'),
  'meta': HljsStyle(color: '#e5e5e5'),
  'meta keyword': HljsStyle(color: '#e5e5e5', bold: true),
  'meta string': HljsStyle(color: '#e5e5e5'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#e2e1e7'),
  'number': HljsStyle(color: '#eb6f92'),
  'operator': HljsStyle(color: '#e0def4'),
  'punctuation': HljsStyle(color: '#e0def4'),
  'quote': HljsStyle(color: '#31748f'),
  'regexp': HljsStyle(color: '#31748f'),
  'section': HljsStyle(color: '#9ccfd8'),
  'selector-tag': HljsStyle(color: '#e2e1e7'),
  'string': HljsStyle(color: '#ebbcba'),
  'strong': HljsStyle(color: '#f6c177', bold: true),
  'subst': HljsStyle(color: '#e0def4'),
  'symbol': HljsStyle(color: '#eb6f92'),
  'tag': HljsStyle(color: '#6e6a86'),
  'template-tag': HljsStyle(color: '#c4a7e7'),
  'template-variable': HljsStyle(color: '#e2e1e7'),
  'title': HljsStyle(color: '#f6c177'),
  'title.class': HljsStyle(color: '#f6c177'),
  'title.class.inherited': HljsStyle(color: '#ebbcba'),
  'title.function': HljsStyle(color: '#9ccfd8'),
  'type': HljsStyle(color: '#c4a7e7'),
  'variable': HljsStyle(color: '#e2e1e7'),
  'variable.constant': HljsStyle(color: '#eb6f92'),
};
