// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/tango` theme.
const base16TangoTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#d3d7cf', backgroundColor: '#2e3436'),
  'addition': HljsStyle(color: '#4e9a06'),
  'attr': HljsStyle(color: '#ef2929'),
  'attribute': HljsStyle(color: '#3465a4'),
  'built_in': HljsStyle(color: '#06989a'),
  'bullet': HljsStyle(color: '#cc0000'),
  'code': HljsStyle(color: '#4e9a06'),
  'comment': HljsStyle(color: '#555753'),
  'deletion': HljsStyle(color: '#cc0000'),
  'doctag': HljsStyle(color: '#06989a'),
  'emphasis': HljsStyle(color: '#75507b', italic: true),
  'keyword': HljsStyle(color: '#75507b'),
  'link': HljsStyle(color: '#ef2929'),
  'literal': HljsStyle(color: '#ef2929'),
  'meta': HljsStyle(color: '#34e2e2'),
  'meta keyword': HljsStyle(color: '#34e2e2', bold: true),
  'meta string': HljsStyle(color: '#34e2e2'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#cc0000'),
  'number': HljsStyle(color: '#ef2929'),
  'operator': HljsStyle(color: '#d3d7cf'),
  'punctuation': HljsStyle(color: '#d3d7cf'),
  'quote': HljsStyle(color: '#06989a'),
  'regexp': HljsStyle(color: '#06989a'),
  'section': HljsStyle(color: '#3465a4'),
  'selector-tag': HljsStyle(color: '#cc0000'),
  'string': HljsStyle(color: '#4e9a06'),
  'strong': HljsStyle(color: '#c4a000', bold: true),
  'subst': HljsStyle(color: '#d3d7cf'),
  'symbol': HljsStyle(color: '#ef2929'),
  'tag': HljsStyle(color: '#729fcf'),
  'template-tag': HljsStyle(color: '#75507b'),
  'template-variable': HljsStyle(color: '#cc0000'),
  'title': HljsStyle(color: '#c4a000'),
  'title.class': HljsStyle(color: '#c4a000'),
  'title.class.inherited': HljsStyle(color: '#4e9a06'),
  'title.function': HljsStyle(color: '#3465a4'),
  'type': HljsStyle(color: '#75507b'),
  'variable': HljsStyle(color: '#cc0000'),
  'variable.constant': HljsStyle(color: '#ef2929'),
};
