// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: file_names, non_constant_identifier_names

import 'package:highlight/highlight_core.dart' show HljsStyle;

/// Highlight.js theme map for the `base16/vulcan` theme.
const base16VulcanTheme = <String, HljsStyle>{
  'root': HljsStyle(color: '#5b778c', backgroundColor: '#041523'),
  'addition': HljsStyle(color: '#977d7c'),
  'attr': HljsStyle(color: '#9198a3'),
  'attribute': HljsStyle(color: '#977d7c'),
  'built_in': HljsStyle(color: '#977d7c'),
  'bullet': HljsStyle(color: '#818591'),
  'code': HljsStyle(color: '#977d7c'),
  'comment': HljsStyle(color: '#7a5759'),
  'deletion': HljsStyle(color: '#818591'),
  'doctag': HljsStyle(color: '#977d7c'),
  'emphasis': HljsStyle(color: '#9198a3', italic: true),
  'keyword': HljsStyle(color: '#9198a3'),
  'link': HljsStyle(color: '#9198a3'),
  'literal': HljsStyle(color: '#9198a3'),
  'meta': HljsStyle(color: '#977d7c'),
  'meta keyword': HljsStyle(color: '#977d7c', bold: true),
  'meta string': HljsStyle(color: '#977d7c'),
  'meta-keyword': HljsStyle(bold: true),
  'name': HljsStyle(color: '#818591'),
  'number': HljsStyle(color: '#9198a3'),
  'operator': HljsStyle(color: '#5b778c'),
  'punctuation': HljsStyle(color: '#5b778c'),
  'quote': HljsStyle(color: '#977d7c'),
  'regexp': HljsStyle(color: '#977d7c'),
  'section': HljsStyle(color: '#977d7c'),
  'selector-tag': HljsStyle(color: '#818591'),
  'string': HljsStyle(color: '#977d7c'),
  'strong': HljsStyle(color: '#adb4b9', bold: true),
  'subst': HljsStyle(color: '#5b778c'),
  'symbol': HljsStyle(color: '#9198a3'),
  'tag': HljsStyle(color: '#6b6977'),
  'template-tag': HljsStyle(color: '#9198a3'),
  'template-variable': HljsStyle(color: '#818591'),
  'title': HljsStyle(color: '#adb4b9'),
  'title.class': HljsStyle(color: '#adb4b9'),
  'title.class.inherited': HljsStyle(color: '#977d7c'),
  'title.function': HljsStyle(color: '#977d7c'),
  'type': HljsStyle(color: '#9198a3'),
  'variable': HljsStyle(color: '#818591'),
  'variable.constant': HljsStyle(color: '#9198a3'),
};
